"""services/stark_docs.py — Stark Industries visual treatment for
important documents JARVIS generates (memos, reports, briefs)."""
import uuid
from datetime import datetime
from pathlib import Path

from config.settings import BASE_DIR

REPORTS_DIR = BASE_DIR / "reports"


class StarkDocs:

    HEADER_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<style>
  body {{ background: #040810; color: #c8eeff;
          font-family: 'Courier New', monospace; padding: 40px; }}
  .stark-header {{
    border-bottom: 2px solid #00b4ff;
    padding-bottom: 20px; margin-bottom: 30px;
  }}
  .stark-logo {{
    font-size: 28px; font-weight: 900;
    letter-spacing: 8px; color: #00b4ff;
    text-shadow: 0 0 20px rgba(0,180,255,0.5);
  }}
  .stark-sub {{
    font-size: 10px; letter-spacing: 4px;
    color: rgba(0,180,255,0.5); margin-top: 4px;
  }}
  .doc-meta {{
    font-size: 11px; color: rgba(0,180,255,0.6);
    letter-spacing: 2px; margin-top: 12px;
  }}
  .doc-title {{
    font-size: 22px; color: #00ffcc;
    letter-spacing: 3px; margin: 30px 0 20px;
    text-transform: uppercase;
  }}
  .section {{ margin: 24px 0; }}
  .section-title {{
    font-size: 11px; letter-spacing: 4px;
    color: #00b4ff; border-left: 3px solid #00b4ff;
    padding-left: 12px; margin-bottom: 12px;
  }}
  .content {{ line-height: 1.8; font-size: 14px; }}
  .stark-footer {{
    border-top: 1px solid rgba(0,180,255,0.2);
    margin-top: 40px; padding-top: 16px;
    font-size: 10px; letter-spacing: 2px;
    color: rgba(0,180,255,0.4);
  }}
  .classification {{
    display: inline-block;
    border: 1px solid #ff3333; color: #ff3333;
    padding: 2px 8px; font-size: 10px;
    letter-spacing: 3px;
  }}
</style>
</head>
<body>
<div class="stark-header">
  <div class="stark-logo">STARK INDUSTRIES</div>
  <div class="stark-sub">ADVANCED INTELLIGENCE DIVISION — J.A.R.V.I.S V5.0</div>
  <div class="doc-meta">
    DOCUMENT ID: {doc_id} &nbsp;|&nbsp;
    GENERATED: {timestamp} &nbsp;|&nbsp;
    <span class="classification">{classification}</span>
  </div>
</div>
<div class="doc-title">{title}</div>
{content}
<div class="stark-footer">
  GENERATED BY J.A.R.V.I.S — JUST A RATHER VERY INTELLIGENT SYSTEM V5.0
  &nbsp;|&nbsp; STARK INDUSTRIES PROPRIETARY
</div>
</body>
</html>
"""

    def generate_report(self, title: str, content: str, classification: str = "INTERNAL") -> dict:
        """Generate a Stark Industries formatted report. Returns
        {doc_id, path} — path is relative to REPORTS_DIR, served via
        GET /stark/docs/{doc_id}."""
        doc_id = str(uuid.uuid4())[:8].upper()
        timestamp = datetime.now().strftime("%Y.%m.%d %H:%M")

        sections = self._format_sections(content)
        html = self.HEADER_TEMPLATE.format(
            doc_id=doc_id, timestamp=timestamp,
            classification=classification, title=title, content=sections,
        )

        REPORTS_DIR.mkdir(parents=True, exist_ok=True)
        path = REPORTS_DIR / f"stark_{doc_id}.html"
        path.write_text(html)

        return {"doc_id": doc_id, "path": str(path)}

    def _format_sections(self, content: str) -> str:
        lines = content.split("\n")
        html = []
        for line in lines:
            if line.startswith("## "):
                html.append(
                    f'<div class="section"><div class="section-title">'
                    f'{line[3:].upper()}</div><div class="content">'
                )
            elif line.startswith("# "):
                html.append(f'<div class="doc-subtitle">{line[2:]}</div>')
            elif line.strip() == "---":
                html.append('</div></div><div class="section">')
            else:
                html.append(f'<p class="content">{line}</p>')
        return "\n".join(html)

    def morning_brief_doc(self, briefing: str) -> dict:
        return self.generate_report("DAILY INTELLIGENCE BRIEFING", briefing, "EYES ONLY")

    def get_report_path(self, doc_id: str) -> Path | None:
        path = REPORTS_DIR / f"stark_{doc_id.upper()}.html"
        return path if path.exists() else None


stark_docs = StarkDocs()
